services:
  - type: web
    name: luffytaro-bot
    runtime: node
    plan: free
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: PREFIX
        value: .
      - key: OWNER_NUMBER
        value: "917866052212"
      - key: SESSION_ID
        value: ""
    disk:
      name: bot-storage
      mountPath: /data
      sizeGB: 1
